name: Train and Evaluate ML Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train Model
        run: python ml_model/train.py

      - name: Evaluate Model
        run: python ml_model/evaluate.py

      - name: Run Tests
        run: pytest

      - name: Save Trained Model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.joblib
